#!/bin/sh
# Create system
mkdir /proc /sys /run
mount -vt proc proc /proc
mount -vt sysfs sysfs /sys
mount -vt tmpfs tmpfs /run
mdev -s

# Network
echo $(cat /etc/hostname) > /proc/sys/kernel/hostname
udhcpc -i eth0

printf "##################################################\n"
printf "##################################################\n"
printf "##          Welcome to phenix project           ##\n"
printf "##################################################\n"
printf "##################################################\n"
